### ISSUE TITLE
Need a license for this repo

### ISSUE THREAD

**Issue by kadler** [IBM/ibmi-oss-docs#1]
We'd like to license this under the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) license, but we've had non-IBM contributions that would need to agree to the licensing:

- [x] @aaronbartell
- [x] @jbh 
- [x] @jkyeung 
- [x] @NattyNarwhal 
- [ ] @worksofliam 
- [x] @phpdave 
- [x] @jwoehr 
- [x] @friedkiwi 

I've uploaded licensing docs based off of what libzmq has done for their licensing efforts. You can find the list of commits being re-licensed under your user name at https://github.com/IBM/ibmi-oss-docs/tree/master/.licensing/commits.

Please copy and fill out [template](https://github.com/IBM/ibmi-oss-docs/blob/master/.licensing/relicense-template-cc0.txt) to a file with your GitHub username.md, eg. I would make .licensing/kadler.md. Once this is done, send a PR referencing this issue so we can get a permanent record of your agreement to the relicensing.

**Comment by jbh** [comment]
This license doesn't percolate to those repos listed in the documentation, right? As in, the license won't have any effect on ibmi-dotfiles, I assume?

**Comment by kadler** [comment]
The license would only apply to the documentation listed in the repo. It would not apply to anything linked to by the documentation.

**Comment by NattyNarwhal** [comment]
Yes, this is OK.

**Comment by jwoehr** [comment]
Anything I have contributed maybe relicensed to Creative Commons as you have stated.

**Comment by worksofliam** [comment]
lgtm

**Comment by aaronbartell** [comment]
LGTM (part II)

**Comment by jkyeung** [comment]
I'm fine with anything I've contributed to this repo being relicensed to CC0.

**Comment by kadler** [comment]
Thanks for everyone who has voiced their approval for relicensing. Please follow the updated steps in https://github.com/IBM/ibmi-oss-docs/issues/1#issue-636728046

**Comment by aaronbartell** [comment]
> Thanks for everyone who has voiced their approval for relicensing. Please follow the updated steps in [#1 (comment)](https://github.com/IBM/ibmi-oss-docs/issues/1#issue-636728046)

Good morning, @kadler!  Could you give me access to create a PR?

**Comment by kadler** [comment]
@aaronbartell You should be able to fork the repo to create a PR

**Comment by friedkiwi** [comment]
Fine for me!

**Comment by kadler** [comment]
Thanks everyone who's filled this out!

Only @worksofliam, @phpdave, and @friedkiwi left to fill out the licensing statement.

**Comment by phpdave** [comment]
Hi Kevin

I had only 1 commit. Can you just remove my commit.  

-Dave

**Comment by kadler** [comment]
Commits can't be removed without rewriting the entire history of the repo.

**Comment by kadler** [comment]
@phpdave it looks like changes you made have been modified since then and are no longer in the current content (though they still exist in the history). I think we can ignore them then and we'll just say that the contents of the repo at the time of the licensing is covered under the CC0, while previous content is not.

**Comment by kadler** [comment]
I would still like to see @friedkiwi and @worksofliam submit a sign-off PR, though the contents of their commits may be small enough that it's unnecessary.

**Comment by friedkiwi** [comment]
@kadler what exactly do you want me to do? fork + send a PR with that file?

**Comment by friedkiwi** [comment]
See https://github.com/IBM/ibmi-oss-docs/pull/14 - is this acceptable?

**Comment by kadler** [comment]
Yep, thanks!
