### ISSUE TITLE
IBMi and AIX package.

### ISSUE THREAD

**Issue by sgonchigar** [IBM/ibmi-oss-docs#151]
### What documentation would you like added?
Would a AIX .bff package be installed on IBMi. If yes, could you provide the steps. 
Trying to install this AIX package 
https://app.datadoghq.com/account/settings/agent/latest?_gl=1%2A1sd548m%2A_gcl_au%2ANDcwMjc3Njk3LjE2OTU2NTY0NjA.%2A_ga%2AMTMzMzE2NTcyNS4xNzAyNDA5MjY3%2A_ga_KN80RDFSQK%2AMTcwMjgxMTMzOC4xMS4xLjE3MDI4MTEzNjMuMC4wLjA.%2A_fplc%2AQlZOam5YNTZUeiUyRjIlMkZJcEpiM0JDb21LN1ViZkpmMXR1NW9Wekt0V00lMkJOMEN4Sm5QZ1IlMkYlMkIxYk81MXNKSkFvbWYwRlhwNnQyemt2NVIlMkJyMlllMTk5eHBaVW0yZG9mc3VIUEpUVSUyRnlrc01rcExJWU93VWhtOUl1NFlWWnglMkY4USUzRCUzRA..&platform=aix

**Comment by kadler** [comment]
No, AIX packages cannot be installed on IBM i.

**Comment by sgonchigar** [comment]
Thank you for that information. Just for the clarification does that include unix/linux packages as well?

**Comment by kadler** [comment]
Not sure what type of packages you're referring to, but unless something says it's compatible with IBM i I would assume it is not compatible. Software built for Linux, FreeBSD, or other platforms are certainly not binary compatible. You may be able to build them from source, but certainly not run their binaries.

**Comment by sgonchigar** [comment]
Thank you!
