### ISSUE TITLE
Determine doc format

### ISSUE THREAD

**Issue by kadler** [IBM/ibmi-oss-docs#2]
Options include:
- readthedocs.io
- GitHub pages
- custom GH wiki integration?
- etc...

## Read the Docs

readthedocs.io is designed for building and serving documentation from a git repository. It uses [Sphinx](https://www.sphinx-doc.org) to build the docs. The default doc format is ReStructuredText, though it can be used with MarkDown with [a plugin](https://www.sphinx-doc.org/en/master/usage/markdown.html). I don't believe all of the features are available with the MarkDown plugin, though.

## GH Pages

GH Pages is a static site generator and publisher. It defaults to using Jekyll to build its website, however it will serve up any HTML files that are in the master branch. By using a different branch to store the source, a custom GH action can be used that generates the HTML from the source and pushes to the master branch. In this way, the source can be stored in _any_ format and anything that can be run in GH actions can be employed. While this could use Sphinx, just like ReadTheDocs, another option would be to use [mkdocs](https://www.mkdocs.org/) which is like Sphinx, but is designed to work with MarkDown instead of ReStructuredText.

## GH Wiki

A GitHub Wiki is easy to use, but rather simplistic. It allows users to open the Wiki only to users with push access _or_ **everyone** with no middle ground. Though the Wiki is stored in a git repo internally, there is currently no way to send PRs to that repo. Workarounds [do exist](https://stackoverflow.com/a/11481887) however.

One way we could do this is to have this repo contain the same format as the wiki repo and then submit PRs to this repo. Then, a custom GH action could be written that force-pushes the merged changes to the wiki. Users would no longer be able to directly edit the wiki, though.

One limitation of the GH Wiki is that its navigational features are rather limiting. The default sidebar contains a flat list of pages. If you want to impose a hierarchy on it, you must create a custom sidebar: https://help.github.com/en/github/building-a-strong-community/creating-a-footer-or-sidebar-for-your-wiki

**Comment by ThePrez** [comment]
`+1` for GitHub pages, since I believe that's the easiest, and we don't need to learn much new technology to keep it up to date. Also, near-zero currency cost when landing contributions. 

`-100` for GitHub wiki, since that's too "Free-for-all" and this is supposed to be an IBM-curated set of docs.

**Comment by kadler** [comment]
After playing around with this yesterday, we've decided on using Sphinx with markdown (using recommonmark) and hosted on readthedocs.io.
