### ISSUE TITLE
yum-utils missing yum-complete-transaction

### ISSUE THREAD

**Issue by mikeb909** [IBM/ibmi-oss-docs#54]
repoquery --list yum-utils shows no such executable in the bin directory.  The man page was installed: /QOpenSys/pkgs/share/man/man8/yum-complete-transaction.8

The version of yum-utils I have:
yum-utils.noarch               1.1.31-6                @ibm 

When attempting to update a package, I got this notice

There are unfinished transactions remaining. You might consider running yum-complete-transaction first to finish them.

which is why I went searching for that command.

**Comment by abmusse** [comment]
It should be installed at: `/QOpenSys/pkgs/sbin/yum-complete-transaction`

**Comment by kadler** [comment]
It's at `/QOpenSys/pkgs/sbin/yum-complete-transaction`. We should probably move it from sbin to bin

**Comment by mikeb909** [comment]
Yep.  Found it.  Want me to close the issue or leave it open until it is moved.

**Comment by kadler** [comment]
We can close it. How to handle sbin is an ongoing issue for us.
